### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by vlasvlasvlas** [clothesnetwork/geohash36#1]
hi! after installing it (ruby 2.1 needed please add that to install doc)

> sudo gem install geohash36

i got this. great:

> Thanks for installing Geohash36 !
> Successfully installed geohash36-0.3.1
> Parsing documentation for geohash36-0.3.1
> Done installing documentation for geohash36 after 0 seconds
> 1 gem installed

but then after:

> geohash36 config:generate

i got:

> /usr/local/bin/geohash36:23:in `load': cannot load such file -- /var/lib/gems/2.1.0/gems/geohash36-0.3.1/bin/geohash36 (LoadError)
>        from /usr/local/bin/geohash36:23:in`<main>'

so.. how do i continue installation? thanks!

**Comment by vlasvlasvlas** [comment]
i got this : 

> ruby 2.1.3p242 (2014-09-19 revision 45877) [i386-linux-gnu]
> 
> Gem 2.2.2

**Comment by vlasvlasvlas** [comment]
> gem list 

andand (1.3.3)
bigdecimal (1.2.4)
bundler (1.7.4)
geohash36 (0.3.1)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
os (0.9.6)
psych (2.0.5)
ptools (1.2.6)
rake (10.1.0)
rdoc (4.1.0)
ruby-try (1.1.1)
test-unit (2.1.3.0)
thor (0.19.1)

**Comment by vlasvlasvlas** [comment]
And this:
when i enter:

> geohash36

i got the same error:

> /usr/local/bin/geohash36:23:in `load': cannot load such file -- /var/lib/gems/2.1.0/gems/geohash36-0.3.1/bin/geohash36 (LoadError)
>        from /usr/local/bin/geohash36:23:in`<main>'

**Comment by vlasvlasvlas** [comment]
also this: 

> ls /var/lib/gems/2.1.0/gems/geohash36-0.3.1/bin/geohash36

give me an OK:

> /var/lib/gems/2.1.0/gems/geohash36-0.3.1/bin/geohash36

**Comment by vlasvlasvlas** [comment]
Whats inside my /usr/local/bin/geohash36:

---

```
#!/usr/bin/ruby2.1
#
# This file was generated by RubyGems.
#
# The application 'geohash36' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

gem 'geohash36', version
load Gem.bin_path('geohash36', 'geohash36', version)

```

**Comment by vlasvlasvlas** [comment]
resolved! must do everything as root, sudo does not do the work.

**Comment by rennhak** [comment]
Thanks for the feedback! Will make sure to fix this for future users.

**Comment by vlasvlasvlas** [comment]
:)
