### ISSUE TITLE
PostGIS Function?

### ISSUE THREAD

**Issue by vlasvlasvlas** [clothesnetwork/geohash36#2]
Hi! are you planning to implement geohash36 as a postgis function?

would be great!!

**Comment by rennhak** [comment]
Interesting idea, yeah, lets keep this for future improvement of geohash36. Thanks for the feedback, much appreciated !

**Comment by vlasvlasvlas** [comment]
What We Have Accomplished is 
- Using plsh ( https://github.com/petere/plsh ) we "call" a bash script thats using geohash36.

And so we create 2 functions inside postgres:

---

postgres@cartodb:/root$ psql
psql (9.1.9, server 9.1.11)
Type "help" for help.

postgres=# select geohash36_decode('9LVB4BH89g');

##           geohash36_decode

 Latitude: 40.689 Longitude: -74.044
(1 row)

postgres=# select geohash36_encode(40.689167,-74.044445);

##  geohash36_encode

 9LVB4BH89g
(1 row)

postgres=#

---

It works fine, but this requires plsh + delicate permissions issues

**Comment by vlasvlasvlas** [comment]
ok i found some kind of solution.

Here are the details:

http://gis.stackexchange.com/questions/121700/geohash36-for-postgis/

i'm still working on a pl/ruby solution.
